language: java
language: node_js
node_js:
  - "11.0"
install: skip
os: linux
dist: trusty
jdk: oraclejdk11
before_script:
  - npm install -g @angular/cli
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - npm install
  - npm run build
  - ./buildTravis.sh
