language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk8

script:
- chmod +x build.sh
  - chmod +x ./fxmanager-auth/gradlew build --scan -s
  - chmod +x ./fxmanager-management/gradlew build --scan -s