language: java
install: skip
os: linux
dist: trusty
jdk: oraclejdk11
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - ./buildTravis.sh
