export const messages = {

    "exito": "Exito",
    "error": "Error",
    "administration.confirm.titulo": "Por favor confirme la acción",

    "baseform.actions.button.clean": "Limpiar",
    "baseform.actions.button.save": "Guardar",
    "basecrud.actions.button.edit": "Modificar",
    "basecrud.actions.button.delete": "Eliminar",
    "basecrud.actions.button.new": "Nuevo",
    "basecrud.actions.button.search": "Buscar",
    "basecrud.confirm.delete.title": "Confirmación",
    "basecrud.confirm.save.title.success": "Confirmación",
    "basecrud.confirm.save.title.error": "Mensaje de error",
    "basecrud.confirm.edit.title.success": "Confirmación",
    "basecrud.confirm.delete.title.success": "Confirmación",
    "confirm.button.yes": "Si",
    "confirm.button.no": "No",
    "basecrud.table.link.next": "Cargar las siguientes ?1 filas",
    "baseservice.msg.default.exception.summary": "Exception",
    "baseservice.msg.default.unauthorized.summary": "Acceso denegado",
    "baseservice.msg.default.unauthorized.detail": "No tiene permisos para realizar esta petición",
    "baseservice.msg.default.error.summary": "Exception",
    "baseservice.msg.default.error.detail": "Ha ocurrido un error al procesar la petición",

    "administration.security.login.bad_credentials":"Usuario o contraseña incorrecta",
    "global.security.error.access.denied":"No tiene permisos suficientes para realizar esta función",
    "global.security.error.general":"Ha ocurrido un error en la comunicación con el servidor, or favor intentelo más tarde.",

    "administration.role.form.title": "Formulario de Rol",
    "administration.role.form.save.msg.success": "Rol creado correctamente",
    "administration.role.form.edit.msg.success": "Rol editado correctamente",
    "administration.role.form.delete.msg.success": "Rol eliminado correctamente",
    "administration.role.form.input.name": "Nombre",
    "administration.role.form.input.btn.add.functionality": "Agregar Funcionalidad",
    "administration.role.form.input.functionality.placeholder":"Seleccione la funcionalidad",
    "administration.role.search.form.title": "Formulario de Rol",
    "administration.role.search.table.title": "Resultados de búsqueda",
    "administration.role.search.column.name": "Nombre",
    "administration.role.confirm.delete.msg": "¿Desea eliminar el rol ?1?",
    


    "administration.resource.form.title": "Formulario de Recurso",
    "administration.resource.form.save.msg.success": "Recurso creado correctamente",
    "administration.resource.form.edit.msg.success": "Recurso editado correctamente",
    "administration.resource.form.delete.msg.success": "Recurso eliminado correctamente",
    "administration.resource.form.input.name": "Nombre",
    "administration.resource.form.input.description": "Descripción",
    "administration.resource.form.input.accesstype": "Tipo de acceso",
    "administration.resource.form.input.uri": "URI",
    "administration.resource.search.form.title": "Formulario de Recurso",
    "administration.resource.search.table.title": "Resultados de búsqueda",
    "administration.resource.search.column.name": "Nombre",
    "administration.resource.confirm.delete.msg": "¿Desea eliminar el recurso ?1?",


    "administration.menu.form.title": "Formulario de Menú",
    "administration.menu.form.save.msg.success": "Menú creado correctamente",
    "administration.menu.form.edit.msg.success": "Menú editado correctamente",
    "administration.menu.form.delete.msg.success": "Menú eliminado correctamente",
    "administration.menu.form.input.name": "Nombre",
    "administration.menu.form.input.index": "Indice",
    "administration.menu.form.input.parent": "Padre",
    "administration.menu.form.input.parent.placeholder": "Seleccione el menú padre",
    "administration.menu.form.input.description": "Descripción",
    "administration.menu.form.input.target": "Uri",
    "administration.menu.search.form.title": "Formulario de Menú",
    "administration.menu.search.table.title": "Resultados de búsqueda",
    "administration.menu.search.column.name": "Nombre",
    "administration.menu.search.column.index": "Indice",
    "administration.menu.search.column.parent": "Padre",
    "administration.menu.search.column.description": "Descripción",
    "administration.menu.search.column.target": "Uri",
    "administration.menu.confirm.delete.msg": "¿Desea eliminar el menú ?1?",

    "administration.functionality.form.title": "Formulario de Funcionalidad",
    "administration.functionality.form.save.msg.success": "Funcionalidad creada correctamente",
    "administration.functionality.form.edit.msg.success": "Funcionalidad editada correctamente",
    "administration.functionality.form.delete.msg.success": "Funcionalidad eliminada correctamente",
    "administration.functionality.form.input.name": "Nombre",
    "administration.functionality.form.input.description": "Descripción",
    "administration.functionality.form.input.menu": "Menú",
    "administration.functionality.form.input.menu.placeholder": "Seleccione el menú",
    "administration.functionality.form.input.resources": "Recursos",
    "administration.functionality.form.input.resources.placeholder": "Seleccione los recursos",
    "administration.functionality.search.form.title": "Formulario de Funcionalidad",
    "administration.functionality.search.table.title": "Resultados de búsqueda",
    "administration.functionality.search.column.name": "Nombre",
    "administration.functionality.search.column.description": "Descripción",
    "administration.functionality.confirm.delete.msg": "¿Desea eliminar la funcionalidad ?1?",


    "administration.moneda.form.title": "Formulario de Moneda",
    "administration.moneda.form.save.msg.success": "Moneda creada correctamente",
    "administration.moneda.form.edit.msg.success": "Moneda editada correctamente",
    "administration.moneda.form.delete.msg.success": "Moneda eliminada correctamente",
    "administration.moneda.form.input.codigo": "Código",
    "administration.moneda.search.form.title": "Formulario de Moneda",
    "administration.moneda.search.table.title": "Resultados de búsqueda",
    "administration.moneda.search.column.codigo": "Código",
    "administration.moneda.confirm.delete.msg": "¿Desea eliminar la moneda ?1?",
    "administration.moneda.form.input.codigo.required": "El código es obligatorio",
    "administration.moneda.form.input.concepto.required": "El concepto es obligatorio",
    "administration.moneda.form.input.denominaciones.required": "Debe ingresar las denominaciones",
    
    "administration.operacion.confirm.save": "¿Está seguro que desea guardar la operación?",
    "administration.operacion.confirm.titulo": "Por favor confirme la acción",
    "administration.operacion.save.exito": "Operación guardada correctamente",
    "administration.operacion.save.error.turno": "Debe iniciar turno para realizar operaciones",

    "administration.traslado.confirm.titulo" : "¿Está seguro que desea guardar el traslado?",
    "administration.traslado.save.exito": "Traslado guardado correctamente",

    "administration.fondeo.confirm.titulo" : "¿Está seguro que desea guardar el fondeo?",
    "administration.fondeo.save.exito": "Fondeo guardado correctamente",

    'administration.operacion.save.exito.id': "con el ID: ",

    "administration.flujo.extraordinaro.save.exito": "Flujo extraordinario guardado correctamente",
    "administration.flujo.extraordinaro.update.exito": "Flujo extraordinario actualizado correctamente",
    "administration.flujo.confirm.titulo" : "¿Está seguro que desea guardar el flujo?",
    "administration.flujo.extraordinario.confirm.titulo" : "¿Está seguro que desea guardar el flujo extraordinario?",
    "administration.flujo.extraordinario.confirm.update" : "¿Está seguro que desea actualizar el flujo extraordinario?",

    "administration.caja.form.save.msg.success": "Caja creada correctamente",
    "administration.caja.form.edit.msg.success": "Caja editada correctamente",

    "administration.sucursal.save.msg.success": "Sucursal creada correctamente",
    "administration.sucursal.update.msg.success": "Sucursal editada correctamente",

    "administration.save.msg.success": "Guardado correctamente",
    "administration.update.msg.success": "Actualizado correctamente",
    "administration.delete.msg.success": "Eliminado correctamente",

};
