-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 10:16:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smart-auth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smart-auth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart-auth` DEFAULT CHARACTER SET utf8 ;
USE `smart-auth` ;

-- -----------------------------------------------------
-- Table `smart-auth`.`fx`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`fx` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cod` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `concepto` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_UNIQUE` (`cod` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`denominacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`denominacion` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(15,2) NOT NULL,
  `moneda` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fx_denominaciones_idx` (`moneda` ASC),
  CONSTRAINT `fk_fx_denominaciones`
    FOREIGN KEY (`moneda`)
    REFERENCES `smart-auth`.`fx` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`sucursal` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cod` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `chk_principal` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `locked` TINYINT(1) NOT NULL,
  `failed_logins` INT(11) NOT NULL,
  `role` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_idx` (`role` ASC),
  CONSTRAINT `fk_role_users`
    FOREIGN KEY (`role`)
    REFERENCES `smart-auth`.`role` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`usuario` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `user` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC),
  INDEX `fk_user_usuario_idx` (`user` ASC),
  CONSTRAINT `fk_user_usuario`
    FOREIGN KEY (`user`)
    REFERENCES `smart-auth`.`user` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`operacion` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha_operacion` DATETIME NOT NULL,
  `fx_base` BIGINT(20) NOT NULL,
  `fx_oper` BIGINT(20) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `nominal` DECIMAL(14,2) NOT NULL,
  `valor_fx_operacion` DECIMAL(14,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `id_soipc` VARCHAR(45) NULL DEFAULT NULL,
  `valor_valoracion` DECIMAL(14,2) NOT NULL,
  `sucursal` BIGINT(20) NULL DEFAULT NULL,
  `usuario` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fx_operaciones_idx` (`fx_base` ASC),
  INDEX `fk_fx_operaciones_idx1` (`fx_oper` ASC),
  INDEX `fk_sucursal_operaciones_idx` (`sucursal` ASC),
  INDEX `fk_usuario_operaciones_idx` (`usuario` ASC),
  CONSTRAINT `fk_fx_bases`
    FOREIGN KEY (`fx_base`)
    REFERENCES `smart-auth`.`fx` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fx_operaciones`
    FOREIGN KEY (`fx_oper`)
    REFERENCES `smart-auth`.`fx` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursal_operaciones`
    FOREIGN KEY (`sucursal`)
    REFERENCES `smart-auth`.`sucursal` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_operaciones`
    FOREIGN KEY (`usuario`)
    REFERENCES `smart-auth`.`usuario` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`denominacion_operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`denominacion_operacion` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `denominacion` BIGINT(20) NOT NULL,
  `operacion` BIGINT(20) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_denominacion_flujos_idx` (`denominacion` ASC),
  INDEX `fk_operacion_flujos_idx` (`operacion` ASC),
  CONSTRAINT `fk_denominacion_flujos`
    FOREIGN KEY (`denominacion`)
    REFERENCES `smart-auth`.`denominacion` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_operacion_flujos`
    FOREIGN KEY (`operacion`)
    REFERENCES `smart-auth`.`operacion` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`empresa` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(45) NOT NULL,
  `razon_social` VARCHAR(150) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `ciiu` VARCHAR(150) NOT NULL,
  `concepto` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`menu` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `index` INT(11) NOT NULL,
  `parent` BIGINT(20) NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `target` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_parent_idx` (`parent` ASC),
  CONSTRAINT `fk_menu_children`
    FOREIGN KEY (`parent`)
    REFERENCES `smart-auth`.`menu` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`functionality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`functionality` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(400) NOT NULL,
  `menu` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `menu_UNIQUE` (`menu` ASC),
  INDEX `fk_menu_functionalities_idx` (`menu` ASC),
  CONSTRAINT `fk_menu_functionalities`
    FOREIGN KEY (`menu`)
    REFERENCES `smart-auth`.`menu` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`resource` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `uri` VARCHAR(45) NOT NULL,
  `access_type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`functionality_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`functionality_resource` (
  `functionality` BIGINT(20) NOT NULL,
  `resource` BIGINT(20) NOT NULL,
  PRIMARY KEY (`functionality`, `resource`),
  INDEX `fk_role_permission_permission_idx` (`resource` ASC),
  CONSTRAINT `fk_functionality_resources`
    FOREIGN KEY (`functionality`)
    REFERENCES `smart-auth`.`functionality` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_resource_functionalities`
    FOREIGN KEY (`resource`)
    REFERENCES `smart-auth`.`resource` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`fx_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`fx_sucursal` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fx` BIGINT(20) NOT NULL,
  `sucursal` BIGINT(20) NOT NULL,
  `precio_compra` DECIMAL(15,2) NOT NULL,
  `precio_venta` DECIMAL(15,2) NOT NULL,
  `precio_valoracion` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_fx_sucursal` (`fx` ASC, `sucursal` ASC),
  INDEX `fk_sucursal_fx_sucursales_idx` (`sucursal` ASC),
  INDEX `fk_fx_fx_sucursales_idx` (`fx` ASC),
  CONSTRAINT `fk_fx_fx_sucursales`
    FOREIGN KEY (`fx`)
    REFERENCES `smart-auth`.`fx` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursal_fx_sucursales`
    FOREIGN KEY (`sucursal`)
    REFERENCES `smart-auth`.`sucursal` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role` BIGINT(20) NOT NULL,
  `functionality` BIGINT(20) NOT NULL,
  `access_types` VARCHAR(45) NOT NULL COMMENT 'Lectura, Escritura, Edición, Eliminación',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_role_funct_access` (`role` ASC, `functionality` ASC, `access_types` ASC),
  INDEX `fk_functionality_roles_idx` (`functionality` ASC),
  CONSTRAINT `fk_functionality_roles`
    FOREIGN KEY (`functionality`)
    REFERENCES `smart-auth`.`functionality` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_functionalies`
    FOREIGN KEY (`role`)
    REFERENCES `smart-auth`.`role` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`provision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`provision` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATETIME NOT NULL,
  `fecha_cumplimiento` DATETIME NOT NULL,
  `sucursal` BIGINT(20) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `clase` VARCHAR(45) NOT NULL,
  `fx` BIGINT(20) NOT NULL,
  `monto` DECIMAL(14,2) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursal_provisiones_idx` (`sucursal` ASC),
  INDEX `fk_fx_provisiones_idx` (`fx` ASC),
  CONSTRAINT `fk_fx_provisiones`
    FOREIGN KEY (`fx`)
    REFERENCES `smart-auth`.`fx` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursal_provisiones`
    FOREIGN KEY (`sucursal`)
    REFERENCES `smart-auth`.`sucursal` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`session` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `user` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_session_user_idx` (`user` ASC),
  CONSTRAINT `fk_user_sessions`
    FOREIGN KEY (`user`)
    REFERENCES `smart-auth`.`user` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`telefono` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NOT NULL,
  `sucursal` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursal_telefonos_idx` (`sucursal` ASC),
  CONSTRAINT `fk_sucursal_telefonos`
    FOREIGN KEY (`sucursal`)
    REFERENCES `smart-auth`.`sucursal` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smart-auth`.`traslado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart-auth`.`traslado` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `sucursal_origen` BIGINT(20) NOT NULL,
  `sucursal_destino` BIGINT(20) NOT NULL,
  `tipo_traslado` VARCHAR(45) NOT NULL,
  `usuario_origen` BIGINT(20) NULL DEFAULT NULL,
  `usuario_destino` BIGINT(20) NULL DEFAULT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `precio_traslado` DECIMAL(14,2) NOT NULL,
  `valor_giro` DECIMAL(14,2) NOT NULL,
  `fx` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_traslados_idx` (`usuario_origen` ASC),
  INDEX `fk_usuario_traslados_idx1` (`usuario_destino` ASC),
  INDEX `fk_fx_traslado_idx` (`fx` ASC),
  INDEX `fk_sucursal_origen_idx` (`sucursal_origen` ASC),
  INDEX `fk_sucursal_destino_idx` (`sucursal_destino` ASC),
  CONSTRAINT `fk_fx_traslado`
    FOREIGN KEY (`fx`)
    REFERENCES `smart-auth`.`fx` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursal_destino`
    FOREIGN KEY (`sucursal_destino`)
    REFERENCES `smart-auth`.`sucursal` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursal_origen`
    FOREIGN KEY (`sucursal_origen`)
    REFERENCES `smart-auth`.`sucursal` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_registrados`
    FOREIGN KEY (`usuario_origen`)
    REFERENCES `smart-auth`.`usuario` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_transferidos`
    FOREIGN KEY (`usuario_destino`)
    REFERENCES `smart-auth`.`usuario` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
