export const FLUJO_CONSTANTES = {
    OPERACION: "OPERACION",
    INVERSION: "INVERSION",
    FINANCIACION: "FINANCIACION",
    NOMINA:"NOMINA",
    PROVEEDORES:"PROVEEDORES",
    SERVICIOS:"SERVICIOS",
    ARRIENDO:"ARRIENDO",
    ADMINISTRACION:"ADMINISTRACION",
    TRANSPORTE:"TRANSPORTE",
    SEGURO:"SEGURO",
    IMPUESTOS:"IMPUESTOS",
    RIESGO:"RIESGO",
    PRESTAMOS:"PRESTAMOS",
    PPE: "PPE",
    HARDWARE: "HARDWARE",
    SOFTWARE: "SOFTWARE",
    DIVIDENDOS: "DIVIDENDOS",
    GENERAL: "GENERAL",
    COMERCIAL: "COMERCIAL",
    ADMINISTRATIVO: "ADMINISTRATIVO",
 
  };
  
